"""
notebook_setup.py — Shared setup for all Spark-ling notebooks.

Usage (first cell of any notebook):
    import sys; sys.path.insert(0, '..')
    from notebooks.notebook_setup import spark, customers_df, accounts_df, transactions_df, branches_df, MODE

Or for manual control:
    from notebooks.notebook_setup import create_spark_session, load_data
    spark, MODE = create_spark_session()
    data = load_data(spark, MODE)

Requirements:
    - .venv activated with databricks-connect==17.3.* installed
    - ~/.databrickscfg with [DEFAULT] host + token
    - S3 data generated via scripts/generate_to_s3.py

See docs/DATABRICKS_CONNECT.md for full setup guide.
"""

S3_RAW   = "s3a://sparkling-data-test/data/raw"
LOCAL_RAW = "../data/raw"


def create_spark_session():
    """
    Create a SparkSession via Databricks Connect (serverless) if available,
    falling back to local PySpark.

    Returns:
        tuple: (spark, mode) where mode is 'databricks' or 'local'

    Example:
        spark, MODE = create_spark_session()
        print(f"Mode: {MODE} | Spark: {spark.version}")
    """
    try:
        from databricks.connect import DatabricksSession
        spark = DatabricksSession.builder.serverless().getOrCreate()
        print(f"✅ Databricks Connect | Spark {spark.version}")
        print( "   Tracking: https://dbc-cdbdfd07-5797.cloud.databricks.com → Job runs")
        return spark, "databricks"

    except Exception as e:
        print(f"⚠️  Databricks Connect unavailable: {e}")
        print("   Falling back to local Spark...")

        import sys
        sys.path.insert(0, "..")
        from configs.spark_config import get_spark_session
        spark = get_spark_session("SparklingLocal")
        print(f"✅ Local Spark {spark.version} | UI: http://localhost:4040")
        return spark, "local"


def load_data(spark, mode: str = "databricks"):
    """
    Load all banking datasets.

    Databricks mode: reads Parquet from S3 (fast, pre-generated by scripts/generate_to_s3.py)
    Local mode:      reads CSV from ../data/raw/ (requires python src/data_generator.py)

    Args:
        spark: active SparkSession
        mode:  'databricks' or 'local'

    Returns:
        dict with keys: branches, customers, accounts, transactions

    Example:
        data = load_data(spark, MODE)
        customers_df = data['customers']
        print(f"Customers: {customers_df.count():,}")
    """
    if mode == "databricks":
        print("📦 Reading Parquet from S3...")
        dfs = {
            "branches":     spark.read.parquet(f"{S3_RAW}/branches"),
            "customers":    spark.read.parquet(f"{S3_RAW}/customers"),
            "accounts":     spark.read.parquet(f"{S3_RAW}/accounts"),
            "transactions": spark.read.parquet(f"{S3_RAW}/transactions"),
        }
    else:
        print("📦 Reading CSV from local data/raw/...")
        from pathlib import Path
        local = Path(LOCAL_RAW)
        if not (local / "customers.csv").exists():
            raise FileNotFoundError(
                "Local data not found. Run: python src/data_generator.py\n"
                "Or switch to databricks mode (see docs/DATABRICKS_CONNECT.md)"
            )
        opts = {"header": True, "inferSchema": True}
        dfs = {
            "branches":     spark.read.csv(str(local / "branches.csv"),     **opts),
            "customers":    spark.read.csv(str(local / "customers.csv"),    **opts),
            "accounts":     spark.read.csv(str(local / "accounts.csv"),     **opts),
            "transactions": spark.read.csv(str(local / "transactions.csv"), **opts),
        }

    print("✅ Data loaded:")
    print(f"   Branches:     {dfs['branches'].count():>8,}")
    print(f"   Customers:    {dfs['customers'].count():>8,}")
    print(f"   Accounts:     {dfs['accounts'].count():>8,}")
    print(f"   Transactions: {dfs['transactions'].count():>8,}")
    return dfs


# ─── Auto-initialization when imported ──────────────────────────────────────
# This runs when you do:  from notebooks.notebook_setup import spark, ...
spark, MODE = create_spark_session()
_data = load_data(spark, MODE)

branches_df     = _data["branches"]
customers_df    = _data["customers"]
accounts_df     = _data["accounts"]
transactions_df = _data["transactions"]


# ─── Module-level exports ───────────────────────────────────────────────────
__all__ = [
    "spark", "MODE",
    "branches_df", "customers_df", "accounts_df", "transactions_df",
    "create_spark_session", "load_data",
    "S3_RAW", "LOCAL_RAW",
]
